version: '3.1'

services:
  auth:
    build:
      context: ./APP/BACKEND
      dockerfile: auth/Dockerfile
#      args:
#        app_env: "development"
#        name: "auth"
#        service_token: "000000"
#        port: "3001"
#        config: "config"
#    env_file:
#      - ./dev.env
    ports:
      - "3000:3000"
#    depends_on:
#        - postgres

  postgres:
    build:
      context: ./APP/BACKEND/MACHINERY
      dockerfile: postgres/Dockerfile
    ports:
      - "5420:5432"
    environment:
      - POSTGRES_USER=miwa
      - POSTGRES_PASSWORD=miwa
      - PGDATA=/pgdata

  redis:
    build:
      context: ./APP/BACKEND/MACHINERY
      dockerfile: redis/Dockerfile
    ports:
      - "6309:6309"